export const PRE_CURATED_COMPANIES = [
  "Aarti Industries",
  "Accenture",
  "Accenture Japan",
  "Accolite",
  "Achnet",
  "Achnet Technology",
  "Adani Institute for Education and Research",
  "Adani Power",
  "Addverb",
  "Addverb Technologies Pvt Ltd",
  "Aditya Birla Capital",
  "Adobe",
  "Adobe India",
  "Aerologiks",
  "Affline Analytics Pvt Ltd",
  "Agnikul Cosmos",
  "Akash Institute",
  "Alphagrep",
  "Amazon",
  "Amazon Berlin",
  "Amazon India",
  "Amazon Luxembourg",
  "AMD",
  "American Express",
  "AMNS",
  "Analog Devices",
  "Angel Broking",
  "Apisero Inc",
  "App Orchid",
  "Applied Materials",
  "Arcesium India Private Limited",
  "Arintra",
  "Arista",
  "Arista Network India Pvt Ltd",
  "Arista Networks",
  "Atlassian",
  "Atotech",
  "AuthBridge",
  "Avalara",
  "Axxela",
  "Axxela Advisory Services",
  "Bajaj Auto",
  "Bakliwal Tutorials",
  "Baldor Technologies",
  "Bank of America",
  "BEL Bengaluru",
  "Betsol",
  "Bloomberg",
  "Bloomberg Pune",
  "Bosch",
  "Bosch Ltd",
  "Bosch Singapore",
  "BPCL",
  "Bridgei2i",
  "Broadridge",
  "Buddi",
  "Burger Singh",
  "Byju's",
  "C-DAC",
  "C1X",
  "Cadence",
  "Cadence Design Systems",
  "Capgemini",
  "Capgemini Technology Services India Ltd",
  "CDAC",
  "Ceremorphic",
  "Cereus Technology",
  "CEWiT",
  "CGI",
  "ChironX",
  "Chryso",
  "CINIF Technology",
  "Cisco",
  "Codenation",
  "Cognam",
  "Cognam Technologies",
  "Cognizant",
  "Cognizant Technology",
  "Commvault",
  "Comvault",
  "Conduent India",
  "Course 5 Intelligence",
  "Cubastion",
  "Curbn",
  "CV Raman Engineering College",
  "CVRS Educational Services",
  "Darwinbox",
  "Dassault",
  "DE Shaw",
  "Delhivery",
  "Deloitte",
  "Dhani",
  "Direct i",
  "Dolcera",
  "Dolcera ITES",
  "Droom",
  "E-Com Express",
  "Elucidata",
  "Endeavor Careers",
  "ERCG",
  "Ericsson",
  "ESI Services Inspired Automation",
  "ET Medialabs",
  "Euler System",
  "Evosysglobal",
  "Expedia",
  "eZDI",
  "Factwise",
  "Fareye",
  "Fiducia",
  "FIIT-JEE",
  "Finisar",
  "Flipkart",
  "Flow Trader",
  "FlytBase",
  "Force Motor",
  "Future First",
  "Gameskraft",
  "Gemini Solutions",
  "Godigit",
  "Gojek",
  "Goldman Sachs",
  "Google",
  "Google India",
  "Green Stack",
  "Gupshup Tech",
  "Halliburton Development Centre India",
  "HCL",
  "HDFC",
  "Helium Consulting",
  "Hero MotoCorp",
  "Housing.com",
  "HPCL",
  "HSBC Technology India",
  "ICICI Bank",
  "Idfy",
  "Imanage",
  "Impact Guru",
  "Increff",
  "Indeed",
  "Indian Oil",
  "Infosys",
  "Infosys Ltd",
  "Inframart",
  "Innominds",
  "Innovaccer",
  "Intel",
  "Intel Corporation",
  "Intuit",
  "iRage Capital",
  "ISRO",
  "Ixigo",
  "J.K Technosoft",
  "Jio Platforms Ltd",
  "JSW",
  "Jubliant",
  "Jungle Works",
  "Jupiter Money",
  "Juspay Technologies",
  "Karza Technologies",
  "KEC",
  "KEC International",
  "Keyideas Infotech",
  "KIIT",
  "Komprise India Pvt Ltd",
  "KPIT",
  "KPRIET",
  "L&T",
  "L&T ECC",
  "L&T Heavy Engineering",
  "L&T Infotech",
  "LafargeHolcim",
  "Land Rover Jaguar",
  "Lava International",
  "Lentra AI",
  "LIDO",
  "Linkdin Inc",
  "Livestreaming",
  "LnT ECC",
  "LnTECC",
  "Logic Fruit",
  "LTI",
  "LTTS",
  "Mahindra & Mahindra",
  "Makemytrip",
  "Makino Auto",
  "Mareana",
  "Maruti Suzuki",
  "Mathworks",
  "Mathworks India Pvt Ltd",
  "Media.net",
  "MediaTek",
  "Medly Pharmacy",
  "Meerut Institute of Engineering & Technology",
  "Mercedes Benz",
  "Merilytics",
  "Microsoft",
  "Microsoft IDC",
  "Microsoft Research",
  "Mirketa Software",
  "Mojo Networks",
  "Morgan Stanley",
  "MTX",
  "Mu-Sigma",
  "NameKart",
  "NCCBM",
  "NetApp",
  "Newzera",
  "Nexus Techno Solutions",
  "NIIT University",
  "Nineleaps",
  "Novartis",
  "NSL Hub",
  "Nucleus Software",
  "NVT Power",
  "Ola",
  "Olacabs",
  "OneBanc",
  "Oneture Technologies Ltd",
  "Optiver",
  "Optum",
  "Oracle",
  "Oyo Rooms",
  "Oyorooms",
  "Parul University",
  "Paytm",
  "Pensando",
  "Perceptive",
  "Perceptive Analytics",
  "Persistent",
  "PI Industries",
  "Pine Labs",
  "Planetspark",
  "Pricol",
  "ProCDNA",
  "Publicis",
  "Publicis Sapient",
  "Pultus Research",
  "Qualcomm",
  "Quantiphi",
  "Quantiphi Analytics Solutions Pvt Ltd",
  "RAAM Group",
  "Radisys",
  "RapidBizApps",
  "RBL Bank",
  "REC",
  "Reliance Jio",
  "RIL (JIO)",
  "Rupeek Fintech",
  "Salesforce",
  "Samsung",
  "Samsung Bangalore",
  "Samsung Delhi",
  "Samsung Noida",
  "Samsung R&D",
  "Sapient",
  "Searce",
  "Servicenow",
  "Shorthillstech",
  "Siemens",
  "Siemens Gamesa",
  "Siemens Healthineers",
  "Sigmoid",
  "Sigmoid Analytics",
  "Signalchip Innovations",
  "Siksha O Anusandhan",
  "Smartcoin",
  "Smartprix",
  "SMS Data",
  "Snapdeal",
  "Soroco India",
  "SpringML",
  "Sprinklr",
  "Square Point Capital",
  "SRI-Bengaluru",
  "SS & C Technologies",
  "Star Union Dai-ichi Life Insurance",
  "Sterlite Technology",
  "Strand Life Sciences",
  "Success Numbers",
  "Suzlon Energy",
  "Taqbit",
  "Tata",
  "Tata Advanced Systems",
  "Tata Consultancy Services",
  "Tata Digital",
  "Tata Motors",
  "Tata Power",
  "TCS",
  "TCS Innovation Lab",
  "Tejas Networks",
  "Tescra",
  "Texas Instruments",
  "Thinket Labs",
  "Tiger Analytics",
  "Titagarh",
  "Toppers",
  "Toppr",
  "Tredence",
  "Trell",
  "Tricon Infotech",
  "Trilogy Innovations",
  "Truminds",
  "TVS Digital",
  "TVS Motors",
  "Uber",
  "Udaan",
  "Unacademy",
  "UnitedHealth Group",
  "Urban Company",
  "Vestas",
  "Viacom",
  "Viacom18",
  "Weather News",
  "Wipro",
  "Wipro Ltd",
  "Wizikey",
  "WOAS Technologies",
  "Wunderman Thompson",
  "Xpressbees",
  "Yodlee",
  "Yugabyte",
  "Zolostays",
  "Zomato",
  "ZS Associates"
];
