export const INDUSTRY_OPTIONS = [
  'Accounting & Auditing',
  'Advertising & Marketing',
  'Aerospace & Defense',
  'Agriculture & Agribusiness',
  'Architecture & Planning',
  'Automotive',
  'Banking & Financial Services',
  'Biotechnology',
  'Chemicals',
  'Civil Engineering & Construction',
  'Computer Hardware',
  'Consulting & Strategy',
  'Consumer Electronics',
  'Consumer Goods & FMCG',
  'Cybersecurity',
  'Data Analytics & Business Intelligence',
  'E-Commerce',
  'Education & EdTech',
  'Electrical & Electronics',
  'Energy & Utilities',
  'Entertainment & Media',
  'Environmental Services',
  'Fashion & Apparel',
  'Food & Beverage',
  'Gaming',
  'Government & Public Sector',
  'Healthcare & Hospitals',
  'Hospitality & Tourism',
  'Human Resources & Staffing',
  'Information Technology & Services',
  'Insurance',
  'Internet of Things (IoT)',
  'Investment Banking & Venture Capital',
  'Legal Services',
  'Logistics & Supply Chain',
  'Machine Learning & AI',
  'Manufacturing',
  'Market Research',
  'Mechanical & Industrial Engineering',
  'Mining & Metals',
  'Non-Profit & NGO',
  'Oil, Gas & Petroleum',
  'Pharmaceuticals',
  'Real Estate',
  'Renewable Energy',
  'Research & Development',
  'Retail',
  'Robotics & Automation',
  'Semiconductors & VLSI',
  'Software Development',
  'Sports & Fitness',
  'Telecommunications',
  'Textiles',
  'Transportation & Mobility',
];
